[app]
hotkey_send = "ctrl+alt+enter"
hotkey_cancel = "ctrl+alt+backspace"
hotkey_list_models = "ctrl+alt+f8"
hotkey_diagnostics = "ctrl+alt+f9"
hotkey_template_default = "ctrl+alt+1"
hotkey_template_translate = "ctrl+alt+2"
autopaste = false

[typewriter]
min_cps = 6
max_cps = 12
jitter_ms = 60
punct_pause_ms = 220
newline_pause_ms = 150
preserve_clipboard = true

[api]
timeout_seconds = 60
max_retries = 3

[privacy]
blocked_patterns = ["sk-[A-Za-z0-9]{20,}", "password=", "Authorization: Bearer "]